# see https://arduino.github.io/arduino-cli/1.0/library-specification/#library-metadata

name=tmg_enc_cpp
version=1.0.0
author=GJW
maintainer=gjwmotor <github.com/gjwmotor>
sentence=Tamagawa encoder, Modbus-RTU Encoder library for Arduino and ESP32
paragraph=This library is Tamagawa or Modbus-Rtu protocol
category=Other
url=https://github.com/gjwmotor/tmg_enc
architectures=*
